### ISSUE TITLE
AccountBook 아이템 수정시 bug

### ISSUE THREAD

**Issue by jangsooji** [jangsooji/se_project#3]
![acc_bug](https://user-images.githubusercontent.com/33803254/33518057-3175eb20-d7d2-11e7-9555-e71122ab1088.png)

수정하고 싶은 아이템의 번호를 입력(첨부한 예시에서 1 입력)한 후, 수정하고 싶은 부분의 번호를 입력할 수 없습니다.
그리고 아이템의 번호가 명시되어 있지 않습니다.

**Comment by jangsooji** [comment]
@jangsooji 테스틍ㅇㅇㅇㅇ

**Comment by Baneul** [comment]
![image](https://user-images.githubusercontent.com/33562569/33521535-7c8f7668-d817-11e7-80d5-5f89239a3fa0.png)
아직 함수 뼈대만 만들고 기능이 없는 상태입니다.

**Comment by Baneul** [comment]
private boolean updateItem (int index) {
 +		int select;
 +		PurchaseRecord pointer =  currentTable.get(index-1);
  		System.out.println("수정하고 싶은 부분의 번호를 입력하세요. (구매 날짜 1, 상품명 2, 금액 3)");
 -		System.out.println(""
 -				+ "");
 +		select=scan.nextInt();
 +		switch(select){
 +		case 1:
 +			 int[] updateDate = inputDatetoArray(scan.next());
 +			 pointer.setDate(updateDate);
 +			 return true;
 +		case 2:
 +			pointer.setName(scan.next());
 +			return false;
 +		case 3:
 +			pointer.setValue(scan.nextInt());		
 +		}
  		return false;
  	}
