### ISSUE TITLE
AccountBook 테스트 버전이 master branch에 존재

### ISSUE THREAD

**Issue by jangsooji** [jangsooji/se_project#4]
![acc_test_del](https://user-images.githubusercontent.com/33803254/33518575-4ec21dfe-d7da-11e7-94db-29d4f3c6cc82.png)

AccountBook 테스트 버전이 master branch에 존재합니다.
branch를 따로 하여 작업합시다.

**Comment by jangsooji** [comment]
+ 아이템 번호 명시
+ 아이템을 comma로 구분하기 보다는 line으로 구분하는 것이 좋지 않을까요?

**Comment by jangsooji** [comment]
@Baneul + 아이템의 번호 명시
+ 아이템을 comma로 구분하기 보다는 line으로 구분하는 것이 좋지 않을까요?

**Comment by jangsooji** [comment]
+ 아이템의 번호 명시
+ 아이템을 comma로 구분하기 보다는 line으로 구분하는 것이 좋지 않을까요? @Baneul

**Comment by jangsooji** [comment]
@jangsooji 테스트

**Comment by jangsooji** [comment]
@jangsooji 테스트트틑222

**Comment by Baneul** [comment]
계산기부분은 수정이 계속 작게 일어나지만 늘 Master로 수정이 일어나고 있습니다. @minahshin

**Comment by minahshin** [comment]
issc02와 hotfix로 브랜치를 두고 수정을했는데 반영이 되지 않았나요?
![image](https://user-images.githubusercontent.com/33835900/33524256-62a1d170-d85c-11e7-8d03-7b06251ff7e7.png)
![image](https://user-images.githubusercontent.com/33835900/33524262-806398c4-d85c-11e7-9349-be19b5d7be6d.png)

**Comment by minahshin** [comment]
아 모르고 close를 해버리고 글을 지웠네요 issc02와 hotfix 브랜치로 merge한 후 push했는데 반영이 안된건가요?
![image](https://user-images.githubusercontent.com/33835900/33524275-c7d51142-d85c-11e7-9b26-199e6f26cd19.png)
![image](https://user-images.githubusercontent.com/33835900/33524277-ccec4c5e-d85c-11e7-8917-124247d44f21.png)

**Comment by Baneul** [comment]
로컬 뿐만 아니라 Github에서도 Branch가 있는데 Github에서는 Master로만 push된 것 같아요!

**Comment by Baneul** [comment]
로컬 뿐만 아니라 Github에서도 Branch가 있는데 Github에서는 Master로만 push된 것 같아요!

**Comment by minahshin** [comment]
확인해보니 로컬에서 branch를 생성하고 중간중간에 git push로 브랜치도 보내줬어야 했었네요! 감사합니다 일단 issc02브랜치는 존재하고 있으니 추가해뒀습니다 :)
![image](https://user-images.githubusercontent.com/33835900/33524415-55d32a62-d860-11e7-86f5-4a1d2e2aeaba.png)
