### ISSUE TITLE
Main에서의 종료 기능이 원활하지 않습니다.

### ISSUE THREAD

**Issue by minahshin** [jangsooji/se_project#7]
@jangsooji @Baneul 
![image](https://user-images.githubusercontent.com/33835900/33524300-c5e0fd82-d85d-11e7-96f4-7b42447a89af.png)
프로그램에서 기능을 사용한 후 Main으로 돌아와서 종료를 누르면 다시 사용했던 기능으로 돌아옵니다
확인해주시고 실행하셨을 때 이러한 오류가 생기면 수정 부탁드립니다 :)

**Comment by jangsooji** [comment]
이 문제는 메인클래스가 아니라 calculator클래스 내에서
fouroperation() 내의 case 2: 부분을 아래와 같이 수정해주시면 될 것 같아요!!
추가적으로 calculator클래스 내의 start() 메소드도 아래와 같이 수정하면 좋을 것 같습니다.
첨부사진은 현재버전 소스인데
우리 프로젝트는 main클래스에서 start메소드를 호출해 계산기기능을 이용하도록 되어있으니
break문만 써주면 반복문이 종료되고 원래의 main으로 돌아갈 것 같습니다.
.
.
.
do {
			System.out.print("새로운 연산을 시작하시겠습니까?(1. Yes / 2. Back to Calculator) : ");
			select_new_op = scan.nextInt();
			System.out.println();
			switch(select_new_op){
			case 1:
				fouroperation();
			break;
			**_case 2:
				break;_**
			default:
				System.out.println("존재하지 않는 메뉴입니다. 다시 다른 메뉴를 선택해 주세요.");
				}
			System.out.println();
		} while(select_new_op!=2);
.
.
.
public void start(){
		int select_cal = 0;
		
		do{	
			System.out.println("---------- Calculator ----------");
			System.out.println("1. 사칙연산\t 2. 단위변환\t 3. Quit Calculator");
			System.out.print("원하는 기능의 번호를 입력하세요: ");
			select_cal=scan.nextInt();
			System.out.println();
			
			switch(select_cal){
			case 1:
				fouroperation();
				break;
			case 2:
				change();
				break;
			case 3:
				break;
			default:
				System.out.print("존재하지 않는 메뉴입니다. 다시 다른 메뉴를 선택해 주세요.");
				break;
			}
		}while(select_cal!=3);
	}
.
.
.

**Comment by minahshin** [comment]
넵 감사합니다 수정 후에 close할게요!
